#include "ui_ipc_response_types.h"
#include "ui_ipc_response_handler.h"
#include "ui_ipc_response_helpers.h"

#define DEFINE_RESULT_HANDLER(functionName, responseType) \
    ROE_S32 functionName(ROE_U8 * msgData) \
    { \
        UI_IPC_RETURN_RESPONSE(msgData, responseType); \
    }

DEFINE_RESULT_HANDLER(UiIpcHandleResponseGetVideoOutputParameters, UiResponseGetVideoOutputParameters)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseGetVideoInputParameters, UiResponseGetVideoInputParameters)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseGetVideoInputCameraParameters, UiResponseGetVideoInputCameraParameters)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseGetVideoInputLowLightParameters, UiResponseGetVideoInputLowLightParameters)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseGetVideoInputInfraredParameters, UiResponseGetVideoInputInfraredParameters)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseGetVideoInputRemoteParameters, UiResponseGetVideoInputRemoteParameters)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseAdjustCameraExposure, UiResponseAdjustCameraExposure)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseGetAudioParameters, UiResponseGetAudioParameters)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseCaptureMediaFile, UiResponseCaptureMediaFile)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseRecordMediaFile, UiResponseRecordMediaFile)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseGetPeripheralUsbParameters, UiResponseGetPeripheralUsbParameters)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseGetPeripheralNetworkParameters, UiResponseGetPeripheralNetworkParameters)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseGetPeripheralCameraModuleParameters, UiResponseGetPeripheralCameraModuleParameters)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseGetPeripheralLowLightModuleParameters, UiResponseGetPeripheralLowLightModuleParameters)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseGetPeripheralInfraredModuleParameters, UiResponseGetPeripheralInfraredModuleParameters)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseGetPeripheralRemoteVideoModuleParameters, UiResponseGetPeripheralRemoteVideoModuleParameters)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseGetPeripheralCompassParameters, UiResponseGetPeripheralCompassParameters)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseGetPeripheralGnssParameters, UiResponseGetPeripheralGnssParameters)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseGetPeripheralRangeFinderParameters, UiResponseGetPeripheralRangeFinderParameters)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseGetPeripheralPanTiltParameters, UiResponseGetPeripheralPanTiltParameters)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseInfraredManualRemoveBadPixel, UiResponseInfraredManualRemoveBadPixel)
DEFINE_RESULT_HANDLER(UiIpcHandleResponseInfraredSdNuc, UiResponseInfraredSdNuc)

#undef DEFINE_RESULT_HANDLER
