#include "ipcMsgQue4UiRcvRes.h"
#include "handleRcvRes.h"

#define DEFINE_RESULT_HANDLER(functionName, responseType) \
    ROE_S32 functionName(ROE_U8 * msgData) \
    { \
        if(!msgData) return ROE_FAILURE; \
        const responseType * response = (const responseType *)msgData; \
        return response->result == 0 ? ROE_SUCCESS : ROE_FAILURE; \
    }

DEFINE_RESULT_HANDLER(handleParseGetVideoOutputParaMsg, RspGetVideoOutputPara_st)
DEFINE_RESULT_HANDLER(handleParseGetVideoInputParaMsg, RspGetVideoInputPara_st)
DEFINE_RESULT_HANDLER(handleParseGetVideoInputCameraParaMsg, RspGetVideoInputCameraPara_st)
DEFINE_RESULT_HANDLER(handleParseGetVideoInputLowLightParaMsg, RspGetVideoInputLowLightPara_st)
DEFINE_RESULT_HANDLER(handleParseGetVideoInputInfraredParaMsg, RspGetVideoInputInfraredPara_st)
DEFINE_RESULT_HANDLER(handleParseGetVideoInputRemoteParaMsg, RspGetVideoInputRemotePara_st)
DEFINE_RESULT_HANDLER(handleParseAdjustCameraExposureMsg, RspAdjustCameraExposure_st)
DEFINE_RESULT_HANDLER(handleParseGetAudioParaMsg, RspGetAudioPara_st)
DEFINE_RESULT_HANDLER(handleParseCaptureMediaFileMsg, RspCaptureMediaFile_st)
DEFINE_RESULT_HANDLER(handleParseRecordMediaFileMsg, RspRecordMediaFile_st)
DEFINE_RESULT_HANDLER(handleParseGetPeripheralUsbParaMsg, RspGetPeripheralUsbPara_st)
DEFINE_RESULT_HANDLER(handleParseGetPeripheralNetworkParaMsg, RspGetPeripheralNetworkPara_st)
DEFINE_RESULT_HANDLER(handleParseGetPeripheralCameraModuleParaMsg, RspGetPeripheralCameraModulePara_st)
DEFINE_RESULT_HANDLER(handleParseGetPeripheralLowLightModuleParaMsg, RspGetPeripheralLowLightModulePara_st)
DEFINE_RESULT_HANDLER(handleParseGetPeripheralInfraredModuleParaMsg, RspGetPeripheralInfraredModulePara_st)
DEFINE_RESULT_HANDLER(handleParseGetPeripheralRemotedVideoModuleParaMsg, RspGetPeripheralRemotedVideoModulePara_st)
DEFINE_RESULT_HANDLER(handleParseGetPeripheralCompassParaMsg, RspGetPeripheralCompassPara_st)
DEFINE_RESULT_HANDLER(handleParseGetPeripheralGnssParaMsg, RspGetPeripheralGnssPara_st)
DEFINE_RESULT_HANDLER(handleParseGetPeripheralRangeFinderParaMsg, RspGetPeripheralRangeFinderPara_st)
DEFINE_RESULT_HANDLER(handleParseGetPeripheralPanTiltParaMsg, RspGetPeripheralPanTiltPara_st)
DEFINE_RESULT_HANDLER(handleParseInfraredManualRemoveBadPixelMsg, RspInfraredManualRemoveBadPixel_st)
DEFINE_RESULT_HANDLER(handleParseInfraredSdNucMsg, RspInfraredSdNuc_st)

#undef DEFINE_RESULT_HANDLER
