#ifndef ZKSL_75_6LC_UI_IPC_PROTOCOL_H
#define ZKSL_75_6LC_UI_IPC_PROTOCOL_H

#include "ui/foundation/roeTypes.h"
#include <stdint.h>

#define UI_RETICLE_NUM 2
#define UI_MAX_MEDIA_FILE_NUM_ONE_PAGE 10
#define UI_MAX_DIVIDING_PLATES_NUM 3
#define UI_IPC_MESSAGE_VERSION 0

/* This is a wire-format header. Keep platform-specific types and pointers out
 * of it so Linux and the Windows simulator use the same byte layout. */
#pragma pack(push, 1)

typedef enum {
    // 通知类型
    MSG_4_NOTIFY_INIT = 0x02000000,

    // 系统功能
    MSG_4_NOTIFY_SYSTEM_OFFSET = 0x02010000,
    MSG_4_NOTIFY_DEVICE_INIT_CONFIG_INFO = MSG_4_NOTIFY_SYSTEM_OFFSET,
    MSG_4_NOTIFY_RESOURCE_PATH_INFO,

    MSG_4_NOTIFY_KEY_EVENT_INFO,
    MSG_4_NOTIFY_MAIN_MENU_OPERATE,
    MSG_4_NOTIFY_DIALOG_BOX_DISP,
    MSG_4_NOTIFY_SYSTEM_BUTT,

    // 射击分划
    MSG_4_NOTIFY_RETICLE_OFFSET = 0x02020000,
    MSG_4_NOTIFY_RETICLE_OVERALL_INFO = MSG_4_NOTIFY_RETICLE_OFFSET,
    MSG_4_NOTIFY_RETICLE_INFO_UPDATING,
    MSG_4_NOTIFY_RETICLE_BUTT,

    // 视频输出显示
    MSG_4_NOTIFY_VIDEO_OUTPUT_OFFSET = 0x02030000,
    MSG_4_NOTIFY_OSD_INFO_SHOW_SWITCH = MSG_4_NOTIFY_VIDEO_OUTPUT_OFFSET,
    MSG_4_NOTIFY_MAIN_DISPLAY_STATUS,
    MSG_4_NOTIFY_VIDEO_ZOOM_INFO,
    MSG_4_NOTIFY_VIDEO_OUTPUT_FREEZING,
    MSG_4_NOTIFY_VIDEO_OUTPUT_MIRROR_FLIP,
    MSG_4_NOTIFY_VIDEO_OUTPUT_ROTATING,
    MSG_4_NOTIFY_VIDEO_OUTPUT_BUTT,

    // 视频采集输入
    MSG_4_NOTIFY_VIDEO_INPUT_OFFSET = 0x02040000,
    MSG_4_NOTIFY_VIDEO_INPUT_DEVICE_STATUS = MSG_4_NOTIFY_VIDEO_INPUT_OFFSET,
    MSG_4_NOTIFY_OBSERVE_MODE,
    MSG_4_NOTIFY_INFRARED_PSEUDO_COLOR_MODE,
    MSG_4_NOTIFY_VIDEO_INPUT_BUTT,

    // 音频输入输出
    MSG_4_NOTIFY_AUDIO_OFFSET = 0x02050000,
    MSG_4_NOTIFY_AUDIO_BUTT,

    // 媒体文件
    MSG_4_NOTIFY_MEDIA_FILE_OFFSET = 0x02060000,
    MSG_4_NOTIFY_CAPTURE_STATUS = MSG_4_NOTIFY_MEDIA_FILE_OFFSET,
    MSG_4_NOTIFY_RECORD_STATUS,
    MSG_4_NOTIFY_MEDIA_FILE_PLAY_OPERATE,
    MSG_4_NOTIFY_MEDIA_FILE_BUTT,

    // 外部设备
    MSG_4_NOTIFY_PERIPHERAL_OFFSET = 0x02070000,

    MSG_4_NOTIFY_PERIPHERAL_GENERAL_OFFSET = MSG_4_NOTIFY_PERIPHERAL_OFFSET,
    MSG_4_NOTIFY_DEVICE_ABILITY = MSG_4_NOTIFY_PERIPHERAL_GENERAL_OFFSET,
    MSG_4_NOTIFY_DEVICE_STATUS,
    MSG_4_NOTIFY_PERIPHERAL_SELF_TEST_INFO,
    MSG_4_NOTIFY_PERIPHERAL_REAL_TIME_INFO,
    MSG_4_NOTIFY_PERIPHERAL_BAT_VOL_INFO,
    MSG_4_NOTIFY_PERIPHERAL_GENERAL_BUTT,

    // 外部设备.网络
    MSG_4_NOTIFY_PERIPHERAL_NETWORK_OFFSET = 0x02070100,
    MSG_4_NOTIFY_PERIPHERAL_NETWORK_BUTT,
    // 外部设备.可见光模组
    MSG_4_NOTIFY_PERIPHERAL_CAMERA_MODULE_OFFSET = 0x02080100,
    MSG_4_NOTIFY_CAMERA_MODULE_AUXILIARY_LIGHTING = MSG_4_NOTIFY_PERIPHERAL_CAMERA_MODULE_OFFSET,
    MSG_4_NOTIFY_PERIPHERAL_CAMERA_MODULE_BUTT,
    // 外部设备.红外模组
    MSG_4_NOTIFY_PERIPHERAL_INFRARED_MODULE_OFFSET = 0x02080200,
    MSG_4_NOTIFY_INFRARED_BAD_PIXEL_THRESHOLD = MSG_4_NOTIFY_PERIPHERAL_INFRARED_MODULE_OFFSET,
    MSG_4_NOTIFY_INFRARED_BAD_PIXEL_NUM,
    MSG_4_NOTIFY_INFRARED_HOT_PIXEL_REPAIRED_CORRECTED_VALUE,
    MSG_4_NOTIFY_PERIPHERAL_INFRARED_MODULE_BUTT,
    // 外部设备.电子罗盘
    MSG_4_NOTIFY_PERIPHERAL_COMPASS_OFFSET = 0x02090100,
    MSG_4_NOTIFY_COMPASS_DATA = MSG_4_NOTIFY_PERIPHERAL_COMPASS_OFFSET,
    MSG_4_NOTIFY_MAGNETIC_DECLINATION,
    MSG_4_NOTIFY_COMPASS_CALIBRATION_SCORE,
    MSG_4_NOTIFY_PERIPHERAL_COMPASS_BUTT,
    // 外部设备.卫星定位
    MSG_4_NOTIFY_PERIPHERAL_GNSS_OFFSET = 0x02090200,
    MSG_4_NOTIFY_GNSS_DATA = MSG_4_NOTIFY_PERIPHERAL_GNSS_OFFSET,
    MSG_4_NOTIFY_PERIPHERAL_GNSS_BUTT,
    // 外部设备.测距机
    MSG_4_NOTIFY_PERIPHERAL_RANGE_FINDER_OFFSET = 0x02090300,
    MSG_4_NOTIFY_RANGE_FINDER_STATUS = MSG_4_NOTIFY_PERIPHERAL_RANGE_FINDER_OFFSET,
    MSG_4_NOTIFY_RANGE_DATA,
    MSG_4_NOTIFY_RANGE_COUNT_DOWN,
    MSG_4_NOTIFY_PERIPHERAL_RANGE_FINDER_BUTT,
    // 外部设备.云台
    MSG_4_NOTIFY_PERIPHERAL_PANTILT_OFFSET = 0x02090400,
    MSG_4_NOTIFY_PANTILT_HORIZONTAL_ANGLE = MSG_4_NOTIFY_PERIPHERAL_PANTILT_OFFSET,
    MSG_4_NOTIFY_PANTILT_VERTICAL_ANGLE,
    MSG_4_NOTIFY_PANTILT_HORIZONTAL_RUNNING_STATUS,
    MSG_4_NOTIFY_PANTILT_VERTICAL_RUNNING_STATUS,
    MSG_4_NOTIFY_PANTILT_OPERATE_INFO,
    MSG_4_NOTIFY_PERIPHERAL_PANTILT_BUTT,

    // 请求响应类型
    MSG_4_REQ_RES_INIT = 0x03000000,
    // 系统功能
    MSG_4_REQ_RES_SYSTEM_OFFSET = 0x03010000,
    MSG_4_REQ_RES_SYSTEM_GENERAL_OFFSET = MSG_4_REQ_RES_SYSTEM_OFFSET,
    MSG_4_REQ_RES_LOG_IN_OUT = MSG_4_REQ_RES_SYSTEM_GENERAL_OFFSET,
    MSG_4_REQ_RES_SHUTDOWN,
    MSG_4_REQ_RES_GET_VERSION_INFO,
    MSG_4_REQ_RES_SET_SYSTEM_TIME,
    MSG_4_REQ_RES_FORMAT_DISK_PARTITION,
    MSG_4_REQ_RES_SYSTEM_GENERAL_BUTT,

    // 系统功能.配置
    MSG_4_REQ_RES_SYSTEM_CONFIG_OFFSET = 0x03010100,
    MSG_4_REQ_RES_RESTORE_FACTORY_SETTING = MSG_4_REQ_RES_SYSTEM_CONFIG_OFFSET,
    MSG_4_REQ_RES_SAVE_LANGUAGE_CONFIG,
    MSG_4_REQ_RES_GET_USER_COMMON_CONFIG,
    MSG_4_REQ_RES_SET_USER_COMMON_CONFIG,
    MSG_4_REQ_RES_GET_USER_MEDIA_CONFIG,
    MSG_4_REQ_RES_SET_USER_MEDIA_CONFIG,
    MSG_4_REQ_RES_SYSTEM_CONFIG_BUTT,
    // 系统功能.用户界面
    MSG_4_REQ_RES_SYSTEM_USER_INTERFACE_OFFSET = 0x03010200,
    MSG_4_REQ_RES_EXIT_MENU_MODE = MSG_4_REQ_RES_SYSTEM_USER_INTERFACE_OFFSET,
    MSG_4_REQ_RES_EXIT_DIALOG_BOX,
    MSG_4_REQ_RES_SYSTEM_USER_INTERFACE_BUTT,

    // 射击分划
    MSG_4_REQ_RES_RETICLE_OFFSET = 0x03020000,
    MSG_4_REQ_RES_RETICLE_GENERAL_OFFSET = MSG_4_REQ_RES_RETICLE_OFFSET,
    MSG_4_REQ_RES_SET_RETICLE_COMMON_CONFIG = MSG_4_REQ_RES_RETICLE_GENERAL_OFFSET,
    MSG_4_REQ_RES_WEAPON_SET_RETICLE_STYLE,
    MSG_4_REQ_RES_WEAPON_SET_RETICLE_COLOR,
    MSG_4_REQ_RES_WEAPON_SET_RETICLE_LUMA,
    MSG_4_REQ_RES_WEAPON_SAVE_CONFIG,
    MSG_4_REQ_RES_WEAPON_OPERATE_MARK_CONFIG,
    MSG_4_REQ_RES_WEAPON_SET_DEFAULT_SHOOT_DISTANCE,
    MSG_4_REQ_RES_WEAPON_OPERATE_SHOOT_DISTANCE,
    MSG_4_REQ_RES_WEAPON_SET_SHOOT_POSITION,
    MSG_4_REQ_RES_WEAPON_SET_SHOOT_ZERO,
    MSG_4_REQ_RES_RETICLE_GENERAL_BUTT,

    // 视频输出显示
    MSG_4_REQ_RES_VIDEO_OUTPUT_OFFSET = 0x03030000,
    MSG_4_REQ_RES_GET_VIDEO_OUTPUT_PARA = MSG_4_REQ_RES_VIDEO_OUTPUT_OFFSET,
    MSG_4_REQ_RES_MAIN_DISPLAY_BRIGHTNESS_ADJUST,
    MSG_4_REQ_RES_MAIN_DISPLAY_CONTRAST_ADJUST,
    MSG_4_REQ_RES_EXTEND_DISPLAY_SWITCH,
    MSG_4_REQ_RES_PIP_SWITCH,
    MSG_4_REQ_RES_VIDEO_ZOOM,
    MSG_4_REQ_RES_VIDEO_OUTPUT_FREEZE,
    MSG_4_REQ_RES_OBJECT_RECOGNITION_SWITCH,
    MSG_4_REQ_RES_VIDEO_OUTPUT_BUTT,

    // 视频采集输入
    MSG_4_REQ_RES_VIDEO_INPUT_OFFSET = 0x03040000,
    MSG_4_REQ_RES_VIDEO_INPUT_GENERAL_OFFSET = MSG_4_REQ_RES_VIDEO_INPUT_OFFSET,
    MSG_4_REQ_RES_GET_VIDEO_INPUT_PARA = MSG_4_REQ_RES_VIDEO_INPUT_GENERAL_OFFSET,
    MSG_4_REQ_RES_MAIN_OBSERVE_MODE_SWITCHING,
    MSG_4_REQ_RES_PIP_OBSERVE_MODE_SWITCHING,
    MSG_4_REQ_RES_VIDEO_INPUT_GENERAL_BUTT,
    // 视频采集输入.可见光
    MSG_4_REQ_RES_VIDEO_INPUT_CAMERA_OFFSET = 0x03040100,
    MSG_4_REQ_RES_GET_VIDEO_INPUT_CAMERA_PARA = MSG_4_REQ_RES_VIDEO_INPUT_CAMERA_OFFSET,
    MSG_4_REQ_RES_CAMERA_DAYNIGHT_MODE_SWITCHING,
    MSG_4_REQ_RES_CAMERA_BRIGHTNESS_ADJUST,
    MSG_4_REQ_RES_CAMERA_CONTRAST_ADJUST,
    MSG_4_REQ_RES_CAMERA_SATURATION_ADJUST,
    MSG_4_REQ_RES_CAMERA_HUE_ADJUST,
    MSG_4_REQ_RES_CAMERA_DEHAZE_SWITCH,
    MSG_4_REQ_RES_CAMERA_DEHAZE_STRENGTH_ADJUST,
    MSG_4_REQ_RES_CAMERA_EXPOSURE_ADJUST,
    MSG_4_REQ_RES_VIDEO_INPUT_CAMERA_BUTT,
    // 视频采集输入.低照度
    MSG_4_REQ_RES_VIDEO_INPUT_LOW_LIGHT_OFFSET = 0x03040200,
    MSG_4_REQ_RES_GET_VIDEO_INPUT_LOW_LIGHT_PARA = MSG_4_REQ_RES_VIDEO_INPUT_LOW_LIGHT_OFFSET,
    MSG_4_REQ_RES_VIDEO_INPUT_LOW_LIGHT_BUTT,
    // 视频采集输入.红外
    MSG_4_REQ_RES_VIDEO_INPUT_INFRARED_OFFSET = 0x03040300,
    MSG_4_REQ_RES_GET_VIDEO_INPUT_INFRARED_PARA = MSG_4_REQ_RES_VIDEO_INPUT_INFRARED_OFFSET,
    MSG_4_REQ_RES_INFRARED_PSEUDOCOLOR_MODE_SWITCHING,
    MSG_4_REQ_RES_INFRARED_BRIGHTNESS_ADJUST,
    MSG_4_REQ_RES_INFRARED_CONTRAST_ADJUST,
    MSG_4_REQ_RES_INFRARED_IMAGE_ENHANCE_ADJUST,
    MSG_4_REQ_RES_INFRARED_SCENARIO_MODE_SWITCHING,
    MSG_4_REQ_RES_INFRARED_HOTSPOT_TRACKING_SWITCH,
    MSG_4_REQ_RES_VIDEO_INPUT_INFRARED_BUTT,
    // 视频采集输入.远程视频
    MSG_4_REQ_RES_VIDEO_INPUT_REMOTE_OFFSET = 0x03040400,
    MSG_4_REQ_RES_GET_VIDEO_INPUT_REMOTE_PARA = MSG_4_REQ_RES_VIDEO_INPUT_REMOTE_OFFSET,
    MSG_4_REQ_RES_VIDEO_INPUT_REMOTE_BUTT,

    // 音频输入输出
    MSG_4_REQ_RES_AUDIO_OFFSET = 0x03050000,
    MSG_4_REQ_RES_AUDIO_GENERAL_OFFSET = MSG_4_REQ_RES_AUDIO_OFFSET,
    MSG_4_REQ_RES_GET_AUDIO_PARA = MSG_4_REQ_RES_AUDIO_GENERAL_OFFSET,
    MSG_4_REQ_RES_AUDIO_BUTT,

    // 媒体文件
    MSG_4_REQ_RES_MEDIA_FILE_OFFSET = 0x03060000,
    MSG_4_REQ_RES_CAPTURE_MEDIA_FILE = MSG_4_REQ_RES_MEDIA_FILE_OFFSET,
    MSG_4_REQ_RES_RECORD_MEDIA_FILE,
    MSG_4_REQ_RES_GET_MEDIA_FILE_LIST,
    MSG_4_REQ_RES_EXIT_PLAYBACK_MEDIA_LIST,
    MSG_4_REQ_RES_DEL_MEDIA_FILE,
    MSG_4_REQ_RES_PLAY_MEDIA_FILE,
    MSG_4_REQ_RES_PLAY_ADJACENT_MEDIA_FILE,
    MSG_4_REQ_RES_STOP_MEDIA_FILE_PLAY,
    MSG_4_REQ_RES_MEDIA_FILE_BUTT,

    // 外部设备
    MSG_4_REQ_RES_PERIPHERAL_OFFSET = 0x03070000,

    // 外部设备.USB
    MSG_4_REQ_RES_PERIPHERAL_USB_OFFSET = 0x03070100,
    MSG_4_REQ_RES_GET_PERIPHERAL_USB_PARA = MSG_4_REQ_RES_PERIPHERAL_USB_OFFSET,
    MSG_4_REQ_RES_PERIPHERAL_USB_BUTT,

    // 外部设备.网络
    MSG_4_REQ_RES_PERIPHERAL_NETWORK_OFFSET = 0x03070200,
    MSG_4_REQ_RES_GET_PERIPHERAL_NETWORK_PARA = MSG_4_REQ_RES_PERIPHERAL_NETWORK_OFFSET,
    MSG_4_REQ_RES_WIFI_SWITCH,
    MSG_4_REQ_RES_GET_WIFI_INFO,
    MSG_4_REQ_RES_PERIPHERAL_NETWORK_BUTT,

    // 外部设备.可见光模组
    MSG_4_REQ_RES_PERIPHERAL_CAMERA_MODULE_OFFSET = 0x03080100,
    MSG_4_REQ_RES_GET_PERIPHERAL_CAMERA_MODULE_PARA = MSG_4_REQ_RES_PERIPHERAL_CAMERA_MODULE_OFFSET,
    MSG_4_REQ_RES_PERIPHERAL_CAMERA_MODULE_BUTT,
    // 外部设备.低照度模组
    MSG_4_REQ_RES_PERIPHERAL_LOW_LIGHT_MODULE_OFFSET = 0x03080200,
    MSG_4_REQ_RES_GET_PERIPHERAL_LOW_LIGHT_MODULE_PARA = MSG_4_REQ_RES_PERIPHERAL_LOW_LIGHT_MODULE_OFFSET,
    MSG_4_REQ_RES_PERIPHERAL_LOW_LIGHT_MODULE_BUTT,
    // 外部设备.红外模组
    MSG_4_REQ_RES_PERIPHERAL_INFRARED_MODULE_OFFSET = 0x03080300,
    MSG_4_REQ_RES_GET_PERIPHERAL_INFRARED_MODULE_PARA = MSG_4_REQ_RES_PERIPHERAL_INFRARED_MODULE_OFFSET,
    MSG_4_REQ_RES_INFRARED_MANUAL_REMOVE_BAD_PIXEL,
    MSG_4_REQ_RES_INFRARED_SET_BAD_PIXEL_THRESHOLD,
    MSG_4_REQ_RES_INFRARED_BAD_PIXEL_OPERATE,
    MSG_4_REQ_RES_INFRARED_HOT_PIXEL_REPAIR_OPERATE,
    MSG_4_REQ_RES_INFRARED_SD_NUC,
    MSG_4_REQ_RES_PERIPHERAL_INFRARED_MODULE_BUTT,
    // 外部设备.远程视频设备
    MSG_4_REQ_RES_PERIPHERAL_REMOTE_VIDEO_MODULE_OFFSET = 0x03080400,
    MSG_4_REQ_RES_GET_PERIPHERAL_REMOTE_VIDEO_MODULE_PARA = MSG_4_REQ_RES_PERIPHERAL_REMOTE_VIDEO_MODULE_OFFSET,
    MSG_4_REQ_RES_PERIPHERAL_REMOTE_VIDEO_MODULE_BUTT,

    // 外部设备.电子罗盘
    MSG_4_REQ_RES_PERIPHERAL_COMPASS_OFFSET = 0x03090100,
    MSG_4_REQ_RES_GET_PERIPHERAL_COMPASS_PARA = MSG_4_REQ_RES_PERIPHERAL_COMPASS_OFFSET,
    MSG_4_REQ_RES_COMPASS_SWITCH,
    MSG_4_REQ_RES_COMPASS_SET_MAGNETIC_DECLINATION,
    MSG_4_REQ_RES_COMPASS_SAVE_CONFIG,
    MSG_4_REQ_RES_COMPASS_START_CALIBRATION,
    MSG_4_REQ_RES_COMPASS_STOP_CALIBRATION,
    MSG_4_REQ_RES_PERIPHERAL_COMPASS_BUTT,
    // 外部设备.卫星定位
    MSG_4_REQ_RES_PERIPHERAL_GNSS_OFFSET = 0x03090200,
    MSG_4_REQ_RES_GET_PERIPHERAL_GNSS_PARA = MSG_4_REQ_RES_PERIPHERAL_GNSS_OFFSET,
    MSG_4_REQ_RES_GNSS_SWITCH,
    MSG_4_REQ_RES_GNSS_POSITION_SYSTEM_SWITCHING,
    MSG_4_REQ_RES_GNSS_COORDINATE_SYSTEM_SWITCHING,
    MSG_4_REQ_RES_PERIPHERAL_GNSS_BUTT,
    // 外部设备.测距机
    MSG_4_REQ_RES_PERIPHERAL_RANGE_FINDER_OFFSET = 0x03090300,
    MSG_4_REQ_RES_GET_PERIPHERAL_RANGE_FINDER_PARA = MSG_4_REQ_RES_PERIPHERAL_RANGE_FINDER_OFFSET,
    MSG_4_REQ_RES_RANGE_FINDER_OPERATE,
    MSG_4_REQ_RES_RANGE_FREQUENCY_ADJUST,
    MSG_4_REQ_RES_RANGE_TIME_DURATION_ADJUST,
    MSG_4_REQ_RES_PERIPHERAL_RANGE_FINDER_BUTT,
    // 外部设备.云台
    MSG_4_REQ_RES_PERIPHERAL_PANTILT_OFFSET = 0x03090400,
    MSG_4_REQ_RES_GET_PERIPHERAL_PANTILT_PARA = MSG_4_REQ_RES_PERIPHERAL_PANTILT_OFFSET,
    MSG_4_REQ_RES_PANTILT_MOVING_CONTROL,
    MSG_4_REQ_RES_PANTILT_MOVING_SPEED_ADJUST,
    MSG_4_REQ_RES_PERIPHERAL_PANTILT_BUTT,

    MSG_4_REQ_RES_BUTT
} UiIpcMessageType;

typedef struct {
    int64_t seconds;
    int64_t microseconds;
} UiIpcTimestamp;

typedef struct {
    ROE_U8 version; // 版本
    ROE_U8 concreteMsgType; // 具体类型
    UiIpcTimestamp timestamp; // 时间戳，秒/微秒
} UiIpcMessageHeader;

#pragma pack(pop)

#if defined(__cplusplus)
static_assert(sizeof(UiIpcTimestamp) == 16, "IPC timestamp layout changed");
static_assert(sizeof(UiIpcMessageHeader) == 18, "IPC message header layout changed");
#else
_Static_assert(sizeof(UiIpcTimestamp) == 16, "IPC timestamp layout changed");
_Static_assert(sizeof(UiIpcMessageHeader) == 18, "IPC message header layout changed");
#endif

static inline ROE_U8 ui_ipc_concrete_type(ROE_SL msgType)
{
    /* Every protocol group stores its local type in the low byte. */
    return (ROE_U8)((ROE_U64)msgType & 0xFFU);
}

#endif // ZKSL_75_6LC_UI_IPC_PROTOCOL_H
